[package]
name = "visual-odometry-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
glob = "0.3.1"
image = "0.25.2"
ndarray = "0.16.1"
patch-tracker = "0.2.1"
rand = "0.8.5"
rand_chacha = "0.3.1"
rerun = "0.17.0"
